<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name'                          => 'ШТУЦЕР УГЛОВОЙ  SWE-L10',
                'description'                   => 'ШТУЦЕР УГЛОВОЙ  SWE-L10 каталожный номер 0002386930 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ШТУЦЕР УГЛОВОЙ  SWE-L10',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'uplotnenie-30x2-n',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6001',
                'catalog_id'                    => '0002386930',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ШТУЦЕР SDS-L10XM14X1,5-TYPEB',
                'description'                   => 'ШТУЦЕР SDS-L10XM14X1,5-TYPEB каталожный номер 0002387120 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ШТУЦЕР SDS-L10XM14X1,5-TYPEB',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'provoloka',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6002',
                'catalog_id'                    => '0002387120',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ГАЙКА 6-ГР. M24',
                'description'                   => 'ГАЙКА 6-ГР. M24 каталожный номер 0002115880 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ГАЙКА 6-ГР. M24',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'gaika-6-gr-m24',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6003',
                'catalog_id'                    => '0002115880',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ШЛАНГ СОЕДИНИТ. 1SN8DN900',
                'description'                   => 'ШЛАНГ СОЕДИНИТ. 1SN8DN900 каталожный номер 0006895500 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ШЛАНГ СОЕДИНИТ. 1SN8DN900',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 7,
                'url_alias'                     => 'shlang-soedinitelnyi-1sn8dn900',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6004',
                'catalog_id'                    => '0006895500',
                'quantity'                      => 100,
                'gallery'                       => json_encode([7]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ГИДРОЦИЛИНДР',
                'description'                   => 'ШЛАНГ СОЕДИНИТ. 1SN8DN900 каталожный номер 0009552911 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ГИДРОЦИЛИНДР',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'gidrotsilindr',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6005',
                'catalog_id'                    => '0009552911',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ШАЙБА КОНТАКТНАЯ A6',
                'description'                   => 'ШАЙБА КОНТАКТНАЯ A6 каталожный номер 0002393860 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ШАЙБА КОНТАКТНАЯ A6',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 8,
                'url_alias'                     => 'shaiba-kontaktnaya-a6',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6006',
                'catalog_id'                    => '0002393860',
                'quantity'                      => 100,
                'gallery'                       => json_encode([8]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ВИНТ 6-ГР. M6X12',
                'description'                   => 'ВИНТ 6-ГР. M6X12 каталожный номер 0002374640 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ВИНТ 6-ГР. M6X12',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 9,
                'url_alias'                     => 'vint-6-gr-m6x12',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6007',
                'catalog_id'                    => '0002374640',
                'quantity'                      => 100,
                'gallery'                       => json_encode([9]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ВТУЛКА РАСПОРНАЯ D32X3X24',
                'description'                   => 'ВТУЛКА РАСПОРНАЯ D32X3X24 каталожный номер 0009051610 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ВТУЛКА РАСПОРНАЯ D32X3X24',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'vtulka-raspornaya-d32x3x24',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6008',
                'catalog_id'                    => '0009051610',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ХОМУТ D1-10X15',
                'description'                   => 'ХОМУТ D1-10X15 каталожный номер 0002154110 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ХОМУТ D1-10X15',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 1,
                'url_alias'                     => 'homut-d1-10x15',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6009',
                'catalog_id'                    => '0002154110',
                'quantity'                      => 100,
                'gallery'                       => json_encode([1]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ],
            [
                'name'                          => 'ВИНТ 6-ГР. M8X20',
                'description'                   => 'ВИНТ 6-ГР. M8X20 каталожный номер 0002362000 подходит для волкообразователя Liner1550. Применяется в узле Гидравлическая система 5001',
                'meta_title'                    => 'ВИНТ 6-ГР. M8X20',
                'meta_description'              => '',
                'meta_keywords'                 => '',
                'image_id'                      => 10,
                'url_alias'                     => 'vint-6-gr-m8x20',
                'price'                         => '0',
                'old_price'                     => '0',
                'articul'                       => '6010',
                'catalog_id'                    => '0002362000',
                'quantity'                      => 100,
                'gallery'                       => json_encode([10]),
                'stock'                         => 1,
                'rating'                        => 4.78,
                'created_at'                    => Carbon::now(),
                'updated_at'                    => Carbon::now()
            ]
        ]);
    }
}
