<?php

namespace App\Http\Controllers;

use App\Models\Settings;
use App\Models\Products;
use App\Models\Modules;
use App\Models\Moduleslideshow;
use App\Models\Categories;
use App\Models\Blog;
use App\Models\News;
use App\Http\Requests;
use App\Models\Image;
use App\Models\HTMLContent;
use App\Models\Attribute;


class MainController extends Controller
{
    public function index(Attribute $attribute, Categories $categories, Image $image, Modules $modules, Moduleslideshow $slideshow)
    {
	    $brands = $attribute->where('name', 'Бренд')->first()->values;
        $women_new_prod = $categories->get_products(1, null, [8 => [113]], ['id', 'desc'], 3, []);
        $men_new_prod = $categories->get_products(2, null, [8 => [113]], ['id', 'desc'], 3, []);
        $big_sizes = $categories->get_products(11, null, [1 => [11]], ['id', 'desc'], 2, []);
        $blog = new News();
        $articles = $blog->where('published', 1)->orderBy('updated_at', 'desc')->paginate(12);

        return view('index')
	        ->with('women_new_prod', $women_new_prod)
	        ->with('men_new_prod', $men_new_prod)
	        ->with('big_sizes', $big_sizes)
	        ->with('brands', $brands)
	        ->with('articles', $articles)
            ->with('slideshow', $slideshow->all());
    }

    /**
     * @param Categories $categories
     * @param Products $products
     * @param Blog $blog
     * @param HTMLContent $html
     * @param null $alias
     * @param null $filters
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function route(Categories $categories, Products $products, News $news, HTMLContent $html, $alias = null, $filters = null){
        $parts = explode('/', str_replace('https://', '', url()->current()));
        $part = end($parts);

        $redirects = array(
            "/brendy/glossi/tovary" => "/catalog/tovary/brend-glossi",
            "/manufacturer/miratti/byproduct_price" => "/catalog/tovary/brend-miratti",
            "/sef_поцена/results631-630" => "/",
            "/404/results1831-1830" => "/",
            "/404/results2071-2070" => "/",
            "/404/results1081-1080" => "/",
            "/sef_поцена/results31-30" => "/",
            "/sef_поцена/results391-390" => "/",
            "/sef_поproduct_popularity/results901-900" => "/",
            "/404/results541-540" => "/",
            "/sef_поцена/results691-690" => "/",
            "/sef_поproduct_popularity/results301-300" => "/",
            "/sef_поцена/results2131-2130" => "/",
            "/sef_поproduct_popularity/results721-720" => "/",
            "/404/results691-690" => "/",
            "/sef_поproduct_popularity/dirasc/results451-450" => "/",
            "/404/sef_поцена/results181-180" => "/",
            "/404/sef_поцена/results781-780" => "/",
            "/404/sef_поцена/results91-90" => "/",
            "/sef_поцена/dirasc/results31-30" => "/",
            "/404/sef_поцена/results301-300" => "/",
            "/sef_поцена/dirasc/results1471-1470" => "/",
            "/404/sef_поцена/results2281-2280" => "/",
            "/404/sef_поproduct_popularity/results1861-1860" => "/",
            "/404/sef_поцена/results331-330" => "/",
            "/производитель/results121-120" => "/brands",
            "/производитель/results181-180" => "/brands",
            "/aktsii/85-detail" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/производитель/startys/sef_поцена" => "/catalog/tovary/brend-startys",
            "/sef_поproduct_popularity/results571-570" => "/",
            "404/sef_поproduct_popularity" => "/",
            "/home" => "/",
            "/sef_поцена" => "/",
            "/404/sef_поproduct_popularity" => "/",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-tufli-komfort" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-tufli-klassika/производитель/results31-30" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-tufli-klassika/производитель/" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-tufli-klassika" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-slipony/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-slipony",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-slipony/производитель/" => "/catalog/zhenskaya-obuv/tip-slipony",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-slipony" => "/catalog/zhenskaya-obuv/tip-slipony",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results82-81" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results55-54" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results163-162" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results136-135" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/results109-108" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki/производитель/" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-sapogi-i-polusapozhki" => "/catalog/zhenskaya-obuv/tip-polysapogki-sapogi",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results82-81" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results55-54" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results406-405" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results379-378" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results352-351" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results325-324" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results298-297" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results28-27" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results271-270" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results244-243" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results217-216" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results190-189" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results163-162" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results136-135" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/results109-108" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto/производитель/" => "/catalog/zhenskaya-obuv",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-vesna-leto" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results82-81" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results55-54" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results28-27" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results244-243" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results217-216" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results190-189" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results163-162" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results136-135" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/results109-108" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima/производитель/" => "/catalog/zhenskaya-obuv/specpredlozhenija-newcollection",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-novinki-osen-zima" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-krossovki" => "/catalog/zhenskaya-obuv/tip-krossovki",
            "/zhenskaia-obuv-vesna-leto/zhenskaya-obuv-espadrili" => "/catalog/zhenskaya-obuv/tip-espadrilyi",
            "/zhenskaia-obuv-vesna-leto/vesennie-botinki" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/uggi-dutiki/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-uggidutiki",
            "/zhenskaia-obuv-vesna-leto/uggi-dutiki/производитель/" => "/catalog/zhenskaya-obuv/tip-uggidutiki",
            "/zhenskaia-obuv-vesna-leto/uggi-dutiki/" => "/catalog/zhenskaya-obuv/tip-uggidutiki",
            "/zhenskaia-obuv-vesna-leto/uggi-dutiki" => "/catalog/zhenskaya-obuv/tip-uggidutiki",
            "/zhenskaia-obuv-vesna-leto/tufli-leto/results28-27" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/tufli-leto" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/zhenskaia-obuv-vesna-leto/topovye-skidki-zhenskaya-raprodazha/производитель/" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/zhenskaia-obuv-vesna-leto/topovye-skidki-zhenskaya-raprodazha" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/zhenskaia-obuv-vesna-leto/shlepantsy-leto/производитель/results55-54" => "/catalog/zhenskaya-obuv/tip-shlepancy",
            "/zhenskaia-obuv-vesna-leto/shlepantsy-leto/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-shlepancy",
            "/zhenskaia-obuv-vesna-leto/shlepantsy-leto/производитель/" => "/catalog/zhenskaya-obuv/tip-shlepancy",
            "/zhenskaia-obuv-vesna-leto/shlepantsy-leto" => "/catalog/zhenskaya-obuv/tip-shlepancy",
            "/zhenskaia-obuv-vesna-leto/sabo/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-sabo",
            "/zhenskaia-obuv-vesna-leto/sabo/производитель/" => "/catalog/zhenskaya-obuv/tip-sabo",
            "/zhenskaia-obuv-vesna-leto/sabo" => "/catalog/zhenskaya-obuv/tip-sabo",
            "/zhenskaia-obuv-vesna-leto/rezinovaya-obuv2014-03-01-13-50-47" => "/catalog/zhenskaya-obuv/tip-rezinovayaobuv",
            "/zhenskaia-obuv-vesna-leto/rezinovaya-obuv/производитель/" => "/catalog/zhenskaya-obuv/tip-rezinovayaobuv",
            "/zhenskaia-obuv-vesna-leto/rezinovaya-obuv" => "/catalog/zhenskaya-obuv/tip-rezinovayaobuv",
            "/zhenskaia-obuv-vesna-leto/letnie-sapozhki" => "/catalog/zhenskaya-obuv/tip-letniesapogki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results82-81" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results55-54" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results190-189" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results163-162" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results136-135" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/results109-108" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki/производитель/" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botinki" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/botilony" => "/catalog/zhenskaya-obuv/tip-botilony",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/manufacturer/" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results91-90" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results61-60" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results31-30" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results181-180" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results151-150" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/results121-120" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/производитель/" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto/" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/bosonozhki-leto" => "/catalog/zhenskaya-obuv/tip-bosonozhki",
            "/zhenskaia-obuv-vesna-leto/baletki-leto/производитель/results55-54" => "/catalog/zhenskaya-obuv/tip-baletki",
            "/zhenskaia-obuv-vesna-leto/baletki-leto/производитель/results28-27" => "/catalog/zhenskaya-obuv/tip-baletki",
            "/zhenskaia-obuv-vesna-leto/baletki-leto/производитель/" => "/catalog/zhenskaya-obuv/tip-baletki",
            "/zhenskaia-obuv-vesna-leto/baletki-leto" => "/catalog/zhenskaya-obuv/tip-baletki",
            "/zhenskaia-obuv-vesna-leto/производитель/vesennie-botinki" => "/catalog/zhenskaya-obuv/tip-botinki",
            "/zhenskaia-obuv-vesna-leto/производитель/rezinovaya-obuv2014-03-01-13-50-47" => "/catalog/zhenskaya-obuv/tip-rezinovayaobuv",
            "/zhenskaia-obuv-vesna-leto" => "/catalog/zhenskaya-obuv",
            "/ukhod-za-obuvyu-to" => "/catalog/uhod",
            "/topovye-skidki/производитель/results28-27" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/topovye-skidki/производитель/" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/topovye-skidki" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/table/vse-pro-obuv/page-2" => "/articles",
            "/table/news/" => "/news",
            "/sumku/sumki-zhenskiye-to" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results91-90" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results61-60" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results31-30" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results181-180" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results151-150" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/results121-120" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumku/muzhskiye-sumki" => "/catalog/muzhskie-aksessuary/tip-sumki",
            "/sumku" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/sumki-to" => "/catalog/zhenskie-aksessuary/tip-sumki",
            "/otzyvy/" => "/reviews",
            "/muzhskiye-sumki" => "/catalog/muzhskie-aksessuary/tip-sumki",
            "/muzhskaya-obuv-vesna-leto/topovye-skidki-muzhskaya-raprodazha/manufacturer/" => "/catalog/muzhskaya-obuv/specpredlozhenija-rasprodazha",
            "/muzhskaya-obuv-vesna-leto/topovye-skidki-muzhskaya-raprodazha" => "/catalog/muzhskaya-obuv/specpredlozhenija-rasprodazha",
            "/muzhskaya-obuv-vesna-leto/shlepantsy" => "/catalog/muzhskaya-obuv/tip-shlepancy",
            "/muzhskaya-obuv-vesna-leto/sandalii" => "/catalog/dlya-muzhchin/tip-sandali",
            "/muzhskaya-obuv-vesna-leto/muzhskie-sapogi" => "/catalog/muzhskaya-obuv/tip-sapogi",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-tufli-komfort" => "/catalog/dlya-muzhchin/tip-tyfli",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-tufli-klassika" => "/catalog/muzhskaya-obuv/tip-tyfli",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-novinki-vesna-leto" => "/catalog/muzhskaya-obuv/specpredlozhenija-newcollection",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-novinki-osen-zima" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-mokasiny" => "/catalog/dlya-muzhchin/tip-mokasiny",
            "/muzhskaya-obuv-vesna-leto/muzhskaya-obuv-krossovki" => "/catalog/dlya-muzhchin/tip-krossovki",
            "/muzhskaya-obuv-vesna-leto/botinki" => "/catalog/muzhskaya-obuv/tip-botinki",
            "/muzhskaya-obuv-vesna-leto/производитель/results82-81" => "/catalog/muzhskaya-obuv",
            "/muzhskaya-obuv-vesna-leto/производитель/results55-54" => "/catalog/muzhskaya-obuv",
            "/muzhskaya-obuv-vesna-leto/производитель/results28-27" => "/catalog/muzhskaya-obuv",
            "/muzhskaya-obuv-vesna-leto/производитель/results109-108" => "/catalog/muzhskaya-obuv",
            "/muzhskaya-obuv-vesna-leto/производитель/" => "/catalog/muzhskaya-obuv",
            "/muzhskaya-obuv-vesna-leto" => "/catalog/muzhskaya-obuv",
            "/manufacturers/venezia" => "/catalog/tovary/brend-venezia",
            "/manufacturers/tuchino" => "/catalog/tovary/brend-tucino",
            "/manufacturers/strado" => "/catalog/tovary/brend-strado",
            "/manufacturers/startys" => "/catalog/tovary/brend-startys",
            "/manufacturers/sprinksolo" => "/catalog/tovary/brend-sprinksolo",
            "/manufacturers/sp-lion" => "/catalog/tovary/brend-splion",
            "/manufacturers/sothby-s" => "/catalog/tovary/brend-sothbys",
            "/manufacturers/solo-man" => "/catalog/tovary/brend-soloman",
            "/manufacturers/shoe-club" => "/catalog/tovary/brend-shoeclub",
            "/manufacturers/selesta" => "/catalog/tovary/brend-selesta",
            "/manufacturers/sart" => "/catalog/tovary/brend-sart",
            "/manufacturers/santi" => "/catalog/tovary/brend-santi",
            "/manufacturers/rav-style-lab" => "/catalog/tovary/brend-ravstylelab",
            "/manufacturers/miratti" => "/catalog/tovary/brend-miratti",
            "/manufacturers/medea" => "/catalog/tovary/brend-medea",
            "/manufacturers/mariposa" => "/catalog/tovary/brend-mariposa",
            "/manufacturers/la-vida" => "/catalog/tovary/brend-lavida",
            "/manufacturers/ksm" => "/catalog/tovary/brend-ksm",
            "/manufacturers/konors" => "/catalog/tovary/brend-konors",
            "/производитель/konors/sef_поцена" => "/catalog/tovary/brend-konors",
            "/manufacturers/keddo" => "/catalog/tovary/brend-keddo",
            "/manufacturers/kadar" => "/catalog/tovary/brend-kadar",
            "/manufacturers/glossi" => "/catalog/tovary/brend-glossi",
            "/manufacturers/geronea" => "/catalog/tovary/brend-geronea",
            "/manufacturers/flex" => "/catalog/tovary/brend-flex",
            "/manufacturers/fashion-footwear" => "/catalog/tovary/brend-fashionfootwear",
            "/manufacturers/dival-dino" => "/catalog/tovary/brend-divalanddino",
            "/manufacturers/dalis" => "/catalog/tovary/brend-dalis",
            "/manufacturers/crosby" => "/catalog/tovary/brend-crosby",
            "/manufacturers/copalo" => "/catalog/tovary/brend-copalo",
            "/manufacturers/bertoni" => "/catalog/tovary/brend-bertoni",
            "/manufacturers/babylon" => "/catalog/tovary/brend-babylon",
            "/manufacturers/aquamarine" => "/catalog/tovary/brend-aquamarine",
            "/manufacturers/alita" => "/catalog/tovary/brend-alita",
            "/manufacturer/alita/byproduct_price" => "/catalog/tovary/brend-alita",
            "/производитель/alita/sef_поцена/dirasc" => "/catalog/tovary/brend-alita",
            "/производитель/alita/sef_поproduct_popularity/dirasc" => "/catalog/tovary/brend-alita",
            "/manufacturers/24m" => "/catalog/tovary/brend-24m",
            "/manufacturer/venezia" => "/catalog/tovary/brend-venezia",
            "/manufacturer/tuchino/results91-90" => "/catalog/tovary/brend-tucino",
            "/manufacturer/tuchino/results61-60" => "/catalog/tovary/brend-tucino",
            "/manufacturer/tuchino/results31-30" => "/catalog/tovary/brend-tucino",
            "/manufacturer/tuchino" => "/catalog/tovary/brend-tucino",
            "/manufacturer/strado/results91-90" => "/catalog/tovary/brend-strado",
            "/manufacturer/strado/results61-60" => "/catalog/tovary/brend-strado",
            "/manufacturer/strado/results31-30" => "/catalog/tovary/brend-strado",
            "/manufacturer/strado" => "/catalog/tovary/brend-strado",
            "/manufacturer/startys" => "/catalog/tovary/brend-startys",
            "/manufacturer/sprinksolo" => "/catalog/tovary/brend-sprinksolo",
            "/manufacturer/spagna" => "/catalog/tovary/brend-spagna",
            "/manufacturer/sp-lion" => "/catalog/tovary/brend-splion",
            "/manufacturer/sothby-s" => "/catalog/tovary/brend-sothbys",
            "/manufacturer/solo-man" => "/catalog/tovary/brend-soloman",
            "/manufacturer/shoe-club" => "/catalog/tovary/brend-shoeclub",
            "/manufacturer/selesta/results91-90" => "/catalog/tovary/brend-selesta",
            "/manufacturer/selesta/results61-60" => "/catalog/tovary/brend-selesta",
            "/manufacturer/selesta/results31-30" => "/catalog/tovary/brend-selesta",
            "/manufacturer/selesta/results121-120" => "/catalog/tovary/brend-selesta",
            "/manufacturer/selesta" => "/catalog/tovary/brend-selesta",
            "/manufacturer/sart" => "/catalog/tovary/brend-sart",
            "/manufacturer/santi" => "/catalog/tovary/brend-santi",
            "/manufacturer/rav-style-lab" => "/catalog/tovary/brend-ravstylelab",
            "/manufacturer/miratti/results91-90" => "/catalog/tovary/brend-miratti",
            "/manufacturer/miratti/results61-60" => "/catalog/muzhskaya-obuv",
            "/manufacturer/miratti/results31-30" => "/catalog/tovary/brend-miratti",
            "/manufacturer/miratti/results151-150" => "/catalog/tovary/brend-miratti",
            "/manufacturer/miratti/results121-120" => "/catalog/tovary/brend-miratti",
            "/manufacturer/miratti" => "/catalog/tovary/brend-miratti",
            "/manufacturer/medea" => "/catalog/tovary/brend-medea",
            "/manufacturer/mariposa/results91-90" => "/catalog/tovary/brend-mariposa",
            "/manufacturer/mariposa/results61-60" => "/catalog/tovary/brend-mariposa",
            "/manufacturer/mariposa/results31-30" => "/catalog/tovary/brend-mariposa",
            "/manufacturer/mariposa" => "/catalog/tovary/brend-mariposa",
            "/manufacturer/la-vida" => "/catalog/tovary/brend-lavida",
            "/manufacturer/ksm" => "/catalog/tovary/brend-ksm",
            "/manufacturer/konors" => "/catalog/tovary/brend-konors",
            "/manufacturer/keddo" => "/catalog/tovary/brend-keddo",
            "/manufacturer/kadar" => "/catalog/tovary/brend-kadar",
            "/manufacturer/glossi" => "/catalog/tovary/brend-glossi",
            "/manufacturer/geronea" => "/catalog/tovary/brend-geronea",
            "/manufacturer/flex/results91-90" => "/catalog/tovary/brend-flex",
            "/manufacturer/flex/results61-60" => "/catalog/tovary/brend-flex",
            "/manufacturer/flex/results31-30" => "/catalog/tovary/brend-flex",
            "/manufacturer/flex" => "/catalog/tovary/brend-flex",
            "/manufacturer/fashion-footwear" => "/catalog/tovary/brend-fashionfootwear",
            "/manufacturer/dival-dino" => "/catalog/tovary/brend-divalanddino",
            "/manufacturer/dalis" => "/catalog/tovary/brend-dalis",
            "/manufacturer/crosby" => "/catalog/tovary/brend-crosby",
            "/manufacturer/copalo" => "/catalog/tovary/brend-copalo",
            "/manufacturer/bertoni" => "/catalog/tovary/brend-bertoni",
            "/manufacturer/babylon" => "/catalog/tovary/brend-babylon",
            "/manufacturer/aquamarine" => "/catalog/tovary/brend-aquamarine",
            "/manufacturer/alita" => "/catalog/tovary/brend-alita",
            "/manufacturer/24m" => "/catalog/tovary/brend-24m",
            "/lost-user-name/" => "/forgotten",
            "/lost-password/" => "/forgotten",
            "/home/zhenskie-tufli2013-07-23-13-06-39" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/home/zhenskie-snikersy" => "/catalog/zhenskaya-obuv/tip-snikersy",
            "/home/zhenskie-polusapozhki" => "/catalog/zhenskaya-obuv/tip-polysapogki",
            "/home/zhenskaya-obuv-osen-zima/results82-81" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results55-54" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results325-324" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results298-297" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results28-27" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results271-270" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results244-243" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results217-216" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results190-189" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results163-162" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results136-135" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima/results109-108" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/zhenskaya-obuv-osen-zima" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results82-81" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results55-54" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results28-27" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results244-243" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results217-216" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results190-189" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results163-162" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results136-135" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima/results109-108" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/muzhskaya-obuv-osen-zima" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/manufacturer/zhenskaya-obuv-osen-zima" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskie-tufli2013-07-23-13-06-39" => "/catalog/zhenskaya-obuv/tip-tyfli",
            "/home/производитель/zhenskie-snikersy" => "/catalog/zhenskaya-obuv/tip-snikersy",
            "/home/производитель/zhenskie-polusapozhki" => "/catalog/zhenskaya-obuv/tip-polysapogki",
            "/home/производитель/zhenskaya-obuv-osen-zima/results82-81" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results55-54" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results325-324" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results298-297" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results28-27" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results271-270" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results244-243" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results217-216" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results190-189" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results163-162" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results136-135" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/zhenskaya-obuv-osen-zima/results109-108" => "/catalog/zhenskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results82-81" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results55-54" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results28-27" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results244-243" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results217-216" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results190-189" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results163-162" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results136-135" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima/results109-108" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/home/производитель/muzhskaya-obuv-osen-zima" => "/catalog/muzhskaya-obuv/sezon-osen-zima",
            "/create-an-account/" => "/registration",
            "/brendy" => "/brands",
            "/aktsii/bolshie-i-malenkie-razmery-dlya-zhenshchin" => "/catalog/dlya-zhenschin/specpredlozhenija-bolshierazmery",
            "/aktsii/bolshie-i-malenkie-razmery-dlya-muzhchin/results28-27" => "/catalog/dlya-muzhchin/specpredlozhenija-bolshierazmery",
            "/aktsii/bolshie-i-malenkie-razmery-dlya-muzhchin" => "/catalog/dlya-muzhchin/specpredlozhenija-bolshierazmery",
            "/aktsii/производитель/results55-54" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/aktsii/производитель/results28-27" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/aktsii/производитель/bolshie-i-malenkie-razmery-dlya-zhenshchin" => "/catalog/dlya-zhenschin/specpredlozhenija-bolshierazmery",
            "/aktsii/производитель/bolshie-i-malenkie-razmery-dlya-muzhchin/results28-27" => "/catalog/dlya-muzhchin/specpredlozhenija-bolshierazmery",
            "/aktsii/производитель/bolshie-i-malenkie-razmery-dlya-muzhchin" => "/catalog/dlya-muzhchin/specpredlozhenija-bolshierazmery",
            "/aktsii/производитель/" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/aktsii" => "/catalog/zhenskaya-obuv/specpredlozhenija-rasprodazha",
            "/производитель/vitto-rossi" => "/catalog/tovary/brend-vittorossi",
            "/производитель/sothby-s/results31-30" => "/catalog/tovary/brend-sothbys",
            "/производитель/selesta/results151-150" => "/catalog/tovary/brend-selesta",
            "/производитель/sart/results31-30" => "/catalog/tovary/brend-sart",
            "/производитель/santi/results91-90" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results61-60" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results31-30" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results271-270" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results241-240" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results211-210" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results181-180" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results151-150" => "/catalog/tovary/brend-santi",
            "/производитель/santi/results121-120" => "/catalog/tovary/brend-santi",
            "/производитель/rondo/results31-30" => "/catalog/tovary/brend-rondo",
            "/производитель/rondo" => "/catalog/tovary/brend-rondo",
            "/производитель/la-pinta/results91-90" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/sef_поproduct_popularity" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/results61-60" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/results31-30" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/results181-180" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/results151-150" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta/results121-120" => "/catalog/tovary/brend-lapinta",
            "/производитель/la-pinta" => "/catalog/tovary/brend-lapinta",
            "/производитель/ksm/results91-90" => "/catalog/tovary/brend-ksm",
            "/производитель/ksm/results61-60" => "/catalog/tovary/brend-ksm",
            "/производитель/ksm/results31-30" => "/catalog/tovary/brend-ksm",
            "/производитель/konors/results91-90" => "/catalog/tovary/brend-konors",
            "/производитель/konors/results61-60" => "/catalog/tovary/brend-konors",
            "/производитель/konors/results31-30" => "/catalog/tovary/brend-konors",
            "/производитель/gattini/results91-90" => "/catalog/tovary/brend-gattini",
            "/производитель/gattini/results61-60" => "/catalog/tovary/brend-gattini",
            "/производитель/gattini/results31-30" => "/catalog/tovary/brend-gattini",
            "/производитель/gattini/results151-150" => "/catalog/tovary/brend-gattini",
            "/производитель/gattini/results121-120" => "/catalog/tovary/brend-gattini",
            "/производитель/gattini" => "/catalog/tovary/brend-gattini",
            "/производитель/davis/results31-30" => "/catalog/tovary/brend-davis",
            "/производитель/davis" => "/catalog/tovary/brend-davis",
            "/производитель/bogun" => "/catalog/tovary/brend-bogun",
            "/производитель/bogun/sef_поцена/dirasc" => "/catalog/tovary/brend-bogun",
            "/производитель/bertoni/results31-30" => "/catalog/tovary/brend-bertoni",
            "/производитель/2u-fashion" => "/catalog/tovary/brend-2ufashion",
            "/производители/vitto-rossi" => "/catalog/tovary/brend-vittorossi",
            "/производители/rondo" => "/catalog/tovary/brend-rondo",
            "/производители/la-pinta" => "/catalog/tovary/brend-lapinta",
            "/производители/gattini" => "/catalog/tovary/brend-gattini",
            "/производители/davis" => "/catalog/tovary/brend-davis",
            "/производители/bogun" => "/catalog/tovary/brend-bogun",
            "/производители/2u-fashion" => "/catalog/tovary/brend-2ufashion",
            "/54-diskontnaya-programma" => "/page/bonusnyya-programma",
            "/50-vozvrat-tovara" => "/page/garantiya-i-vozvrat",
            "/table/news" => "/",
            "/sef_поцена/results61-60" => "/",
            "/sef_поцена/results1981-1980" => "/",
            "/404/results1291-1290" => "/",
            "/404/sef_поцена/dirasc" => "/",
            "/404/results601-600" => "/",
            "/404/results511-510" => "/",
            "/sef_поцена/results361-360" => "/",
            "/sef_поцена/results1681-1680" => "/",
            "/sef_поцена/results1021-1020" => "/",
            "/sef_поцена/results91-90" => "/",
            "/404/results1861-1860" => "/",
            "/sef_поцена/dirasc/results1861-1860" => "/",
            "/sef_поцена/dirasc/results2071-2070" => "/",
            "/404/sef_поцена/results1171-1170" => "/",
            "/404/sef_поproduct_popularity/results1921-1920" => "/",
            "/sef_поцена/dirasc/results1111-1110" => "/",
            "/404/sef_поцена/results1351-1350" => "/",
            "/404/sef_поцена/results2161-2160" => "/",
            "/404/sef_поцена/results1411-1410" => "/",
            "/404/sef_поцена/results511-510" => "/",
            "/404/sef_поproduct_popularity/results481-480" => "/",
            "/404/sef_поцена/results1501-1500" => "/",
            "/sef_поproduct_popularity/dirasc/results1081-1080" => "/",
            "/404/sef_поцена/results481-480" => "/",
            "/404/sef_поproduct_popularity/results541-540" => "/",
            "/sef_поproduct_popularity/dirasc/results1291-1290" => "/",
            "/404/sef_поцена/results571-570" => "/",
            "/404/sef_поproduct_popularity/results1291-1290" => "/",
            "/404/sef_поцена/results271-270" => "/",
            "/404/sef_поцена/results1021-1020" => "/",
            "/sef_поproduct_popularity/dirasc/results271-270" => "/",
            "/sef_поцена/dirasc/results1531-1530" => "/",
            "/404/sef_поproduct_popularity/results1651-1650" => "/",
            "/404/sef_поproduct_popularity/results631-630" => "/",
            "/sef_поproduct_popularity/dirasc/results361-360" => "/",
            "/sef_поцена/dirasc/results691-690" => "/",
            "/sef_поцена/dirasc/results2131-2130" => "/",
            "/sef_поцена/dirasc/results1771-1770" => "/",
            "/404/sef_поproduct_popularity/results1681-1680" => "/",
            "/404/sef_поproduct_popularity/results2071-2070" => "/",
            "/производитель/sef_поproduct_popularity/results2191-2190" => "/",
            "/404/sef_поцена/results1381-1380" => "/",
            "/404/sef_поцена/results1471-1470" => "/",
            "/sef_поцена/dirasc/results1681-1680" => "/",
            "/sef_поцена/dirasc/results1831-1830" => "/",
            "/sef_поцена/dirasc/results1801-1800" => "/",
            "/404/sef_поцена/results1321-1320" => "/",
            "/404/sef_поцена/results1051-1050" => "/",
            "/sef_поproduct_popularity/dirasc/results541-540" => "/",
            "/sef_поproduct_popularity/dirasc/results391-390" => "/",
            "/sef_поproduct_popularity/dirasc/results661-660" => "/",
            "/sef_поцена/dirasc/results2191-2190" => "/",
            "/manufacturer/sekada" => "/brands",
            "/производитель" => "/brands",
            "/производитель/results1021-1020" => "/brands",
            "/производитель/sef_поproduct_popularity/results151-150" => "/brands",
            "/производитель/2u-fashion/sef_поцена/dirasc" => "/catalog/tovary/brend-2ufashion",
            "/производитель/konors/sef_поцена/results91-90" => "/catalog/tovary/brend-konors",
            "/manufacturers/strimm" => "/catalog/tovary/brend-strimm",
            "/manufacturer/meglias" => "/catalog/tovary/brend-meglias",
            "/производитель/bogun/sef_поцена" => "/catalog/tovary/brend-bogun",
            "/manufacturers/franco-lucci" => "/catalog/tovary/brend-francolucci",
            "/manufacturer/miratti/byproduct_popularity" => "/catalog/tovary/brend-miratti",
            "/manufacturers/marco-pinotti" => "/catalog/tovary/brend-marcopinotti",
            "/manufacturers/pier-lucci" => "/catalog/tovary/brend-pierlucci",
            "/manufacturer/venezia/byproduct_price" => "/catalog/tovary/brend-venezia",
            "/manufacturer/ksm/byproduct_price" => "/catalog/tovary/brend-ksm",
            "/производитель/ksm/sef_поproduct_popularity/dirasc" => "/catalog/tovary/brend-ksm",
            "/производитель/ksm/sef_поцена/dirasc" => "/catalog/tovary/brend-ksm",
            "/производитель/babylon/sef_поцена" => "/catalog/tovary/brend-babylon",
            "/производитель/copalo/sef_поцена" => "/catalog/tovary/brend-copalo",
            "/manufacturer/marco-pinotti" => "/catalog/tovary/brend-marcopinotti",
            "/create-an-account" => "/registration",
            "/lost-user-name" => "/forgotten",
            "/производитель/tuchino/results121-120" => "/catalog/tovary/brend-tuchino",
            "/производитель/startys/sef_поцена/dirasc" => "/catalog/tovary/brend-startys",
            "/производитель/startys/sef_поproduct_popularity/dirasc" => "/catalog/tovary/brend-startys",
            "/производитель/konors/sef_поproduct_popularity/dirasc" => "/catalog/tovary/brend-konors",
            "/производитель/vitto-rossi/sef_поцена" => "/catalog/tovary/brend-vittorossi",
            "/производитель/alita" => "/catalog/tovary/brend-alita",
            "/производитель/la-vida/sef_поцена" => "/catalog/tovary/brend-lavida",
            "/производитель/la-vida/sef_поproduct_popularity/dirasc" => "/catalog/tovary/brend-lavida",
            "/производитель/sothby-s/dirasc" => "/catalog/tovary/brend-sothbys"
        );

        if(isset($redirects[urldecode(str_replace(env('APP_URL', 'https://tyfli.com'), '', url()->current()))])){
            return redirect($redirects[urldecode(str_replace(env('APP_URL', 'https://tyfli.com'), '', url()->current()))], 301);
        }elseif($categories->where('url_alias', $part)->count()){
            return redirect()->action(
                'CategoriesController@show', ['alias' => $part], 301
            );
        }elseif(count($parts) > 2 && $products->where('url_alias', str_replace('-detail', '', $part))->count()){
            return redirect()->action(
                'ProductsController@show', ['alias' => str_replace('-detail', '', $part)], 301
            );
        }elseif(count($parts) == 2 && $news->where('url_alias', $part)->count()){
            return redirect()->action(
                'NewsController@show', ['alias' => $part], 301
            );
        }elseif(count($parts) == 2 && $html->where('url_alias', $part)->count()){
            return redirect()->action(
                'HTMLContentController@show', ['alias' => $part], 301
            );
        }elseif(in_array(substr($part, -4), ['.jpg', '.png', 'jpeg'])){
            $image = new Image();
            return redirect('/uploads/no_image.jpg', 301);
        }

        return abort(404);
    }
}
